name: paynow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  equatable: ^2.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  google_fonts: ^8.2.1
  mobile_scanner: ^7.4.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Valley Sans
      fonts:
        - asset: assets/fonts/ValleySans-Regular.ttf
        - asset: assets/fonts/ValleySans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ValleySans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ValleySans-Bold.ttf
          weight: 700
